/**
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements. See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership. The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied. See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { InterestPeriod } from './interestPeriod';
import { Money } from './money';
import { MonetaryCurrency } from './monetaryCurrency';
import { LoanProductMinimumRepaymentScheduleRelatedDetail } from './loanProductMinimumRepaymentScheduleRelatedDetail';
import { InterestPeriodMc } from './interestPeriodMc';


export interface RepaymentPeriod { 
    calculatedDueInterest: Money;
    calculatedDuePrincipal?: Money;
    capitalizedIncomePrincipal?: Money;
    creditedAmounts?: Money;
    creditedInterest?: Money;
    creditedPrincipal?: Money;
    currency?: MonetaryCurrency;
    dueDate?: string;
    dueInterest?: Money;
    duePrincipal?: Money;
    emi?: Money;
    emiPlusCreditedAmountsPlusFutureUnrecognizedInterest?: Money;
    firstInterestPeriod?: InterestPeriod;
    firstRepaymentPeriod?: boolean;
    fromDate?: string;
    fullyPaid?: boolean;
    futureUnrecognizedInterest?: Money;
    initialBalanceForEmiRecalculation?: Money;
    interestMoved?: boolean;
    interestPeriods?: Array<InterestPeriod>;
    lastInterestPeriod?: InterestPeriod;
    loanProductRelatedDetail?: LoanProductMinimumRepaymentScheduleRelatedDetail;
    mc?: InterestPeriodMc;
    originalEmi?: Money;
    outstandingInterest?: Money;
    outstandingLoanBalance?: Money;
    outstandingPrincipal?: Money;
    paidInterest?: Money;
    paidPrincipal?: Money;
    previous?: RepaymentPeriod;
    rateFactorPlus1?: number;
    totalCapitalizedIncomeAmount?: Money;
    totalCreditedAmount?: Money;
    totalDisbursedAmount?: Money;
    totalPaidAmount?: Money;
    unrecognizedInterest?: Money;
    zero?: Money;
}

